definitions:
  api.createRatingRequest:
    properties:
      description:
        maxLength: 200
        minLength: 3
        type: string
      dishID:
        type: string
    required:
    - description
    - dishID
    type: object
  api.ratingResponse:
    properties:
      description:
        type: string
      dishID:
        type: string
      id:
        type: string
      restaurantID:
        type: string
      sentiment:
        type: string
    type: object
  api.restaurantResponse:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /ratings:
    post:
      consumes:
      - application/json
      description: create a rating
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: RestaurantID header
        in: header
        name: RestaurantID
        required: true
        type: string
      - description: Create rating
        in: body
        name: rating
        required: true
        schema:
          $ref: '#/definitions/api.createRatingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.ratingResponse'
            type: array
      summary: Create a rating
      tags:
      - ratings
  /restaurants:
    get:
      consumes:
      - application/json
      description: list restaurants
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.restaurantResponse'
            type: array
      summary: List restaurants
      tags:
      - restaurants
swagger: "2.0"
